[server]
port=53
listen_mode=local
; listen_mode=all

; Single explicit binds:
; bind_ipv4=127.0.0.1
; bind_ipv6=::1

; Or multiple explicit binds:
; bind_ipv4=127.0.0.1, 10.0.0.5
; bind_ipv6=::1, 200:ffff::1

[upstreams]
dns=1.1.1.1, 8.8.8.8, [2606:4700:4700::1111]:53

[logging]
file=/var/log/rn.log
queries=false



